matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-25.0.0
          - android-25
      sudo: required
#    - os: osx
#      osx_image: xcode8.3
#      language: objective-c
#      addons:
#        firefox: latest
git:
  depth: 100000
before_install:
# - sudo apt-get install xvfb
- rvm use system
- export LANG=en_US.UTF-8
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./scripts/install-jdk.sh; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then nvm install v8.10.0; nvm use v8.10.0; fi
- node -v
- npm install -g npm@6.1.0
- npm -v
- npm install -g typescript@2.6.2
- tsc -v
- npm install -g cordova ionic
- npm install -g karma-cli
before_script:
# - export DISPLAY=:99.0
- "./scripts/add-key.sh"
script:
- npm install
# - xvfb-run karma start karma.conf.js --single-run --browsers Firefox
- "./scripts/update-app-version.sh"
- "./scripts/build.sh"
- "./scripts/upload-to-hockeyapp.sh || travis_terminate 1"
env:
  global:
  - PROFILE_NAME="4d823e71-5ff3-4b23-99fb-6d5ba7ffd783"
  - secure: SaKdh0CCGywWY2J4GmL9uzDw4EnyGESs3DVHddfSpxhCItByJSBM2OIYXAdNRH1s+dStHbOejvlYqnPoDap8jIZ9EGi9Sv2K32yqVXlUp7Ku82cr6b0m7EV+xvMC/kDT7Tt1PKjrtsrvxVDJFLuMle0ZETR5bCUZ7i3ay8E+4uBUP3SloWFed+6NGV8FVybX1fCCr3mfwNFGOGSOIAzdwtLq2k/NkhXZI1FPxzoewkhgweUnAhoGlaEcp53n6yRwxGnoHhi6HZAD1z21W5uyZ8kqATxO+p4haxOA3mFsGdAXYodGyz1e3T+o4IjJy45HyZai/0mq9jaKp48k1g0xX1MQFdenr4nBhfloknKSvvxRBpB5ryWZ1dTqzO28HScMgPGxhe2KFR9QIZydNaJYUo1kWwP2XRFdSSGTSLy/fY4ri1/WsnP1+9RPE3NhjvHMcfJmIDr91kTl3yhPB6N2RYzb7s/FfUyg11r7conTGltOygDJrdyPnOa25DAv0bKH5R33GSpRQ+2PbELvrAun0w9bDVfXh67hikF2xbppV87se3sFnXCQHAhsOfE3xRj7X/geU1Hpden+LqkXVu6OK6V4Zt2Lne9nU5k9J1JL2KWdE3jtAlR2Yadpr4lbewXfZgepgEVOPeDA4Cs7QkHocSB47skcdWhoFNFmCU/Xl/g=
  - secure: KNO3otEigz8nUSVW5pUFtiQUIR0UegRuHDwiQLqSvYI3MVzg11/HYkqzl+TgkS8LF7qC/GhWDlAxEsmI7vloKh5kC+BJeXoxlXbTjkam63AeeZAi01mthULwRhSlYJuPfKoLNLivOqLoHl3dvQOhNyUKSCqPv/qbRQDRMjd0s/vLPdQC66souwImhghZPT8oCkIAahYvXmwwhHS9VmT5kQrexWKlRgVcaPxk18PUH3YtVa0UoL/9mKI+DP5i93eC/hZ4HxSghsTjSb8xOsj4cilKKLzgjUk4WxPjhSMDvglfvmBPQ2A3SJcFLYaM7zPMqzvAJC1aOYhAZ+75u8twRbj/TG8y6/Fgj26UV9GvXEU3PvIynbd749TR5Bf/Im0LbZy6A/EBx5/ryi1znRZNG0icLFh+KalaCDIlRbpxjKvPzhYORXKV8DoNFADWbg1nlSdMlxMxBrk9c7zBeopu0CN0JEd2K5PZzPFBQ5O+mgU47gvx72rDC4rBZqjoedtj7cwbK624ZcOBiRmxTg40QEGTDT15tVZ4uueW6C5hBWwNP6LGdg7iPSmDZu28K+zCLpPUllYWYnwqvBW744wkwDuuSNRI+JkzdBaj0DMEczkNMQPQkXYCeEsmj51n/HBlDQaAd42xKkv/HxasAUrhF2fdfdF+RmygOkUVQfGmkm4=
licenses:
    - '.+'
