matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-25.0.0
          - android-25
      sudo: required
    - os: osx
      osx_image: xcode8.2
      language: objective-c
      addons:
        firefox: latest
cache:
  directories:
  - node_modules
git:
  depth: 100000
before_install:
- rvm use system
- export LANG=en_US.UTF-8
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./scripts/install-jdk.sh; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then nvm install node; nvm use node; fi
- npm -v
- node -v
- npm install -g cordova ionic
- npm install -g angular-cli
- npm install -g karma
before_script:
- export DISPLAY=:99.0
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sh -e /etc/init.d/xvfb start; fi  
- "./scripts/add-key.sh"
script:
- npm install
- mkdir www
- karma start karma.conf.js --single-run --browsers Firefox
- "./scripts/update-app-version.sh"
- "./scripts/build.sh"
after_success:
- "./scripts/upload-to-hockeyapp.sh"
env:
  global:
  - PROFILE_NAME="3b8e7193-a3f0-49df-91a7-37b4dfb59d5b"
  - secure: SaKdh0CCGywWY2J4GmL9uzDw4EnyGESs3DVHddfSpxhCItByJSBM2OIYXAdNRH1s+dStHbOejvlYqnPoDap8jIZ9EGi9Sv2K32yqVXlUp7Ku82cr6b0m7EV+xvMC/kDT7Tt1PKjrtsrvxVDJFLuMle0ZETR5bCUZ7i3ay8E+4uBUP3SloWFed+6NGV8FVybX1fCCr3mfwNFGOGSOIAzdwtLq2k/NkhXZI1FPxzoewkhgweUnAhoGlaEcp53n6yRwxGnoHhi6HZAD1z21W5uyZ8kqATxO+p4haxOA3mFsGdAXYodGyz1e3T+o4IjJy45HyZai/0mq9jaKp48k1g0xX1MQFdenr4nBhfloknKSvvxRBpB5ryWZ1dTqzO28HScMgPGxhe2KFR9QIZydNaJYUo1kWwP2XRFdSSGTSLy/fY4ri1/WsnP1+9RPE3NhjvHMcfJmIDr91kTl3yhPB6N2RYzb7s/FfUyg11r7conTGltOygDJrdyPnOa25DAv0bKH5R33GSpRQ+2PbELvrAun0w9bDVfXh67hikF2xbppV87se3sFnXCQHAhsOfE3xRj7X/geU1Hpden+LqkXVu6OK6V4Zt2Lne9nU5k9J1JL2KWdE3jtAlR2Yadpr4lbewXfZgepgEVOPeDA4Cs7QkHocSB47skcdWhoFNFmCU/Xl/g=
  - secure: hnB0fLI8pWzSRKQgn7PUgM8GAQ4ttZOxuwPDP/93MqjQ4siWdU/8Tp9ylmJRp9CcBPpFPz/iz/LG0BZSh7NFnNSWsFVQuW2BhtQoL5c64jbQKBP9UH/o4AVgooSg+YTvcd9kFAZKit5jxwiaO7qooUFInP9lqrZMat1D+Tch1RbkIDCEz1UHljn9wzeM5bTwyvyg3bz0wKt4e2rTpYugAXhYr8lxgJvmRsFkDP1cLzzt6n3vsqyK+lGC4ZKZArPO3h+nsfQWuQJ7csXn0joQbcrIEqATFANCZ9O6w3EMqaHlt0C1/Vb4LlWej2nf2ZdkkjixdcWTsnQzeuoC+KzWAsW4QgJULydsLz2eqjA2FgLpZNuQUj34bjP1xK9JphhNFyflmOJGzDvsKVjj+sUgto6UDFbRa6c2S6ez/wXprQtQ3tT20XT/+0O/o5wVFFP0DZO395BXqy8xmaSsSQCCN71HLR5ljpZNpySyuB0srakdTCtzFZOmd+pIxE5w373dhszgGCeIBkiIIYO0MjS/9+CHNeZvz9NPZ0jtF1yu71N+E0UivAgfcxW6i10SdluXmgrh2Z+ISPFmlQOSV3KYA6x1tNpTKWs9+cg3plPu0qo8mC+y5DkpjZv2fBffOHtD9dDuecbYavkPn3ZnxT6o7tmXMR66RwdMcf3Xbt64BiM=
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
